version: 2.1

# jobs definitions
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Test
          command: mvn clean test
      - run:
          name: JaCoCo post-test execution
          command: sh ./jacocoPostExec.sh
      - run:
          name: SonarCloud analysis
          command: mvn sonar:sonar -Dsonar.projectKey=massimostanzione_isw2-proj1plus
          
# invoking jobs via workflows
workflows:
  build-and-test:
    jobs:
      - build-and-test
