version: 2.1

# jobs definitions
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Test
          command: mvn clean test || true
      - run:
          name: JaCoCo post-test execution
          command: sh ./jacocoPostExec.sh
      - run:
          name: Prepare artifacts
          command: |
            mkdir -p /tmp/isw2-proj1plus
            cp -r ~/project/target/jacoco-gen /tmp/isw2-proj1plus
      - store_artifacts:
          path: /tmp/isw2-proj1plus

# invoking jobs via workflows
workflows:
  build-and-test:
    jobs:
      - build-and-test
