version: 2.1

# jobs definitions
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Test
          command: mvn clean test
      - run:
          name: JaCoCo post-test execution
          command: ./jacocoPostExec.sh
          
# invoking jobs via workflows
workflows:
  build-and-test:
    jobs:
      - build-and-test
